

public class CronogramaAuto extends javax.swing.JFrame {
    int aula;
    float hora;
    public CronogramaAuto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        mat = new javax.swing.JButton();
        port = new javax.swing.JButton();
        Tec = new javax.swing.JButton();
        soci = new javax.swing.JButton();
        caixa7 = new javax.swing.JTextField();
        caixa6 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        caixa8 = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 172, 238));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Cronograma", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("OCR A Extended", 0, 16), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Informe a quantidade de aulas:");

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Informe o tempo de cada aula:");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Informe a área de conhecimento desejada:");

        mat.setBackground(new java.awt.Color(85, 188, 215));
        mat.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        mat.setText("Matemática");
        mat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                matActionPerformed(evt);
            }
        });

        port.setBackground(new java.awt.Color(85, 188, 215));
        port.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        port.setText("Português");
        port.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                portActionPerformed(evt);
            }
        });

        Tec.setBackground(new java.awt.Color(85, 188, 215));
        Tec.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        Tec.setText("História");
        Tec.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TecActionPerformed(evt);
            }
        });

        soci.setBackground(new java.awt.Color(85, 188, 215));
        soci.setFont(new java.awt.Font("OCR A Extended", 0, 12)); // NOI18N
        soci.setText("Biologia");
        soci.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sociActionPerformed(evt);
            }
        });

        caixa7.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        caixa7.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caixa7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa7ActionPerformed(evt);
            }
        });

        caixa6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        caixa6.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        caixa6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                caixa6ActionPerformed(evt);
            }
        });

        caixa8.setColumns(20);
        caixa8.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        caixa8.setRows(5);
        caixa8.setText("Plano de Aula");
        jScrollPane1.setViewportView(caixa8);

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Cronograma recomendado:");

        jButton5.setBackground(new java.awt.Color(85, 188, 215));
        jButton5.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton5.setText("<");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setBackground(new java.awt.Color(85, 188, 215));
        jButton6.setFont(new java.awt.Font("OCR A Extended", 0, 14)); // NOI18N
        jButton6.setText("x");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(85, 188, 215));
        jButton1.setFont(new java.awt.Font("OCR A Extended", 2, 12)); // NOI18N
        jButton1.setText("Imprimir");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(caixa7, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(caixa6, javax.swing.GroupLayout.PREFERRED_SIZE, 350, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(179, 179, 179))
                                    .addComponent(Tec, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(soci, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(27, 27, 27))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(31, 31, 31)))
                        .addGap(4, 4, 4))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(141, 141, 141)
                        .addComponent(jButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addComponent(jButton6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(2, 2, 2))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(77, 77, 77))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE, false)
                    .addComponent(mat, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tec, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(soci, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(port, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(28, 28, 28)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixa6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(11, 11, 11)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(caixa7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 8, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton1)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void matActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_matActionPerformed
      this.dispose();
      new Imprimir().setVisible(true);
      aula=Integer.valueOf(caixa6.getText());
      hora=Float.valueOf(caixa7.getText());
      caixa8.setText(verificaMatematica(aula, hora));
    }//GEN-LAST:event_matActionPerformed

    private void caixa7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa7ActionPerformed

    private void caixa6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_caixa6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_caixa6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
this.dispose();
new AreadeConhecimento().setVisible(true);
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
this.dispose();
new CronogramaAuto().setVisible(false);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void TecActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TecActionPerformed

      aula=Integer.valueOf(caixa6.getText());
      hora=Float.valueOf(caixa7.getText());
      caixa8.setText(verificaTecnologia(aula, hora));
    }//GEN-LAST:event_TecActionPerformed

    private void portActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_portActionPerformed

      aula=Integer.valueOf(caixa6.getText());
      hora=Float.valueOf(caixa7.getText());
      caixa8.setText(verificaPortugues(aula, hora));
    }//GEN-LAST:event_portActionPerformed

    private void sociActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sociActionPerformed

      aula=Integer.valueOf(caixa6.getText());
      hora=Float.valueOf(caixa7.getText());
      caixa8.setText(verificaSociologia(aula, hora));
    }//GEN-LAST:event_sociActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CronogramaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CronogramaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CronogramaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CronogramaAuto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CronogramaAuto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Tec;
    private javax.swing.JTextField caixa6;
    private javax.swing.JTextField caixa7;
    private javax.swing.JTextArea caixa8;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton mat;
    private javax.swing.JButton port;
    private javax.swing.JButton soci;
    // End of variables declaration//GEN-END:variables

    private String verificaMatematica(int aula, float hora) {
         String result = null;   
        if((aula==1)&&(hora==30.0))
            result = "Método de aula leve:\n1° Etapa: 10min de explicação do conteúdo.\n2° Etapa: 20min para a turma realizar as atividades e entregar.";
        
        else if((aula==1)&&(hora==50.0))
            result = "Método de aula interativo:\n1° Etapa: 20min de explicação do material.\n2° Etapa: 30min para a realizar uma atividade interativa entre colegas(dicussões).";
                
        else if ((aula==2)&&(hora==30.0))
            result = "Método de aula descritivo:\n1° Etapa: 15min de explicação do material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==2)&&(hora==50.0))
            result = "Método de aula gamificado:\n1° Etapa: 20min de explicação e apresentação do material/jogos.\n2° Etapa: 30min para aplicar o 1° jogos\n3° Etapa: 50min para aplicar 2° jogo, pontuar e comentar.";
               
        else if ((aula==3)&&(hora==30.0))
            result = "Método de aula interativo/descritivo:\n1° Etapa: 15min de explicação do Material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==3)&&(hora==50.0))
            result = "Método de aula Colaborativo:\n1° Etapa: 30min de explicação do conteúdo e criação dos grupos.\n2° Etapa: 60min para a turma realizar as o projeto/atividade.\n3° Etapa: 140min para apresentação de todos os grupos.";
        
        return result;
    }

    private String verificaPortugues(int aula, float hora) {
       String calculo = null;
        if((aula==1)&&(hora==30))
            calculo = "Método de aula leve:\n1° Etapa: 10min de explicação do conteúdo.\n2° Etapa: 20min para a turma realizar as atividades e entregar.";
        
        else if((aula==1)&&(hora==50.0))
            calculo = "Método de aula interativo:\n1° Etapa: 20min de explicação do material.\n2° Etapa: 30min para a realizar uma atividade interativa entre colegas(dicussões).";
        
        else if ((aula==2)&&(hora==30.0))
            calculo = "Método de aula descritivo:\n1° Etapa: 15min de explicação do material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==2)&&(hora==50.0))
            calculo = "Método de aula gamificado:\n1° Etapa: 20min de explicação e apresentação do material/jogos.\n2° Etapa: 30min para aplicar o 1° jogos\n3° Etapa: 50min para aplicar 2° jogo, pontuar e comentar.";
        
        else if ((aula==3)&&(hora==30.0))
            calculo = "Método de aula interativo/descritivo:\n1° Etapa: 15min de explicação do Material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";

                else if((aula==3)&&(hora==50.0))
            calculo = "Método de aula Colaborativo:\n1° Etapa: 30min de explicação do conteúdo e criação dos grupos.\n2° Etapa: 60min para a turma realizar as o projeto/atividade.\n3° Etapa: 140min para apresentação de todos os grupos.";
        
        return calculo;
    }

    private String verificaSociologia(int aula, float hora) {
        String horario = null;
        if((aula==1)&&(hora==30.0))
            horario = "Método de aula leve:\n1° Etapa: 10min de explicação do conteúdo.\n2° Etapa: 20min para a turma realizar as atividades e entregar.";
        
        else if((aula==1)&&(hora==50.0))
            horario = "Método de aula interativo:\n1° Etapa: 20min de explicação do material.\n2° Etapa: 30min para a realizar uma atividade interativa entre colegas(dicussões).";
        
        else if ((aula==2)&&(hora==30.0))
            horario = "Método de aula descritivo:\n1° Etapa: 15min de explicação do material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==2)&&(hora==50.0))
            horario = "Método de aula gamificado:\n1° Etapa: 20min de explicação e apresentação do material/jogos.\n2° Etapa: 30min para aplicar o 1° jogos\n3° Etapa: 50min para aplicar 2° jogo, pontuar e comentar.";
        
        else if ((aula==3)&&(hora==30.0))
            horario = "Método de aula interativo/descritivo:\n1° Etapa: 15min de explicação do Material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==3)&&(hora==50.0))
            horario = "Método de aula Colaborativo:\n1° Etapa: 30min de explicação do conteúdo e criação dos grupos.\n2° Etapa: 60min para a turma realizar as o projeto/atividade.\n3° Etapa: 140min para apresentação de todos os grupos.";
        
        return horario;
    }

    private String verificaTecnologia(int aula, float hora) {
        String cronogra = null;
        if((aula==1)&&(hora==30.0))
            cronogra = "Método de aula leve:\n1° Etapa: 10min de explicação do conteúdo.\n2° Etapa: 20min para a turma realizar as atividades e entregar.";
        
        else if((aula==1)&&(hora==50.0))
            cronogra = "Método de aula interativo:\n1° Etapa: 20min de explicação do material.\n2° Etapa: 30min para a realizar uma atividade interativa entre colegas(dicussões).";
        
        else if ((aula==2)&&(hora==30.0))
            cronogra = "Método de aula descritivo:\n1° Etapa: 15min de explicação do material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==2)&&(hora==50.0))
            cronogra = "Método de aula gamificado:\n1° Etapa: 20min de explicação e apresentação do material/jogos.\n2° Etapa: 30min para aplicar o 1° jogos\n3° Etapa: 50min para aplicar 2° jogo, pontuar e comentar.";
        
        else if((aula==3)&&(hora==30.0))
            cronogra = "Método de aula interativo/descritivo:\n1° Etapa: 15min de explicação do Material.\n2° Etapa: 45min para a turma realizar a atividade descritiva.\nPróxima aula: Debater as dissertações";
        
        else if((aula==3)&&(hora==50.0))
            cronogra = "Método de aula Colaborativo:\n1° Etapa: 30min de explicação do conteúdo e criação dos grupos.\n2° Etapa: 60min para a turma realizar as o projeto/atividade.\n3° Etapa: 140min para apresentação de todos os grupos.";
        
        return cronogra;
    }
}
