package questao5_gui;

/**
 *
 * @author Higor_Diniz
 */
public class Tela_Masculino extends javax.swing.JFrame {

    float Peso, Altura, IMC;
    
    public Tela_Masculino() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 32767));
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        CaixaAltura = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        CaixaPeso = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        CaixaResultado = new javax.swing.JTextArea();
        CaixaCalcular = new javax.swing.JButton();
        CaixaLimpar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        CaixaSair = new javax.swing.JButton();
        CaixaVoltar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 153, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Body Mass", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Times New Roman", 1, 18), new java.awt.Color(0, 51, 255))); // NOI18N

        jLabel2.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        jLabel2.setText("Você está no IMC (Masculino)");

        jLabel3.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        jLabel3.setText("Para continuar, informe os seguintes valores:");

        jLabel4.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        jLabel4.setText("Peso(KG) - Ex (63.2):");

        CaixaAltura.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        jLabel5.setFont(new java.awt.Font("OCR A Extended", 0, 15)); // NOI18N
        jLabel5.setText("Altura(M) - Ex (1.74):");

        CaixaPeso.setFont(new java.awt.Font("Yu Gothic Medium", 0, 14)); // NOI18N

        CaixaResultado.setColumns(20);
        CaixaResultado.setFont(new java.awt.Font("MS Reference Sans Serif", 0, 13)); // NOI18N
        CaixaResultado.setRows(5);
        CaixaResultado.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        jScrollPane1.setViewportView(CaixaResultado);

        CaixaCalcular.setBackground(new java.awt.Color(204, 204, 204));
        CaixaCalcular.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 15)); // NOI18N
        CaixaCalcular.setForeground(new java.awt.Color(0, 0, 153));
        CaixaCalcular.setText("Calcular");
        CaixaCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaCalcularActionPerformed(evt);
            }
        });

        CaixaLimpar.setBackground(new java.awt.Color(204, 204, 204));
        CaixaLimpar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 15)); // NOI18N
        CaixaLimpar.setForeground(new java.awt.Color(0, 0, 153));
        CaixaLimpar.setText("Limpar");
        CaixaLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaLimparActionPerformed(evt);
            }
        });

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/questao5_gui/IMCMasculino1.0 (1).png"))); // NOI18N

        CaixaSair.setBackground(new java.awt.Color(204, 204, 204));
        CaixaSair.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        CaixaSair.setForeground(new java.awt.Color(0, 0, 153));
        CaixaSair.setText("X");
        CaixaSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaSairActionPerformed(evt);
            }
        });

        CaixaVoltar.setBackground(new java.awt.Color(204, 204, 204));
        CaixaVoltar.setFont(new java.awt.Font("Nirmala UI Semilight", 1, 12)); // NOI18N
        CaixaVoltar.setForeground(new java.awt.Color(0, 0, 153));
        CaixaVoltar.setText("<");
        CaixaVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaixaVoltarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addGap(41, 41, 41)
                                .addComponent(CaixaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(CaixaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 109, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(111, 111, 111))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(CaixaCalcular)
                        .addGap(82, 82, 82)
                        .addComponent(CaixaLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(151, 151, 151))))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(CaixaVoltar)
                .addGap(72, 72, 72)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(CaixaSair))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(73, 73, 73)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 417, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addComponent(jLabel2))
                    .addComponent(jLabel3))
                .addContainerGap(81, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(92, 92, 92)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(62, 62, 62)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(CaixaAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 15, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(CaixaPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGap(41, 41, 41)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(CaixaCalcular)
                    .addComponent(CaixaLimpar))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(24, 24, 24)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CaixaSair, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(CaixaVoltar, javax.swing.GroupLayout.Alignment.TRAILING)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CaixaLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaLimparActionPerformed
     CaixaPeso.setText("");
     CaixaAltura.setText("");
     CaixaResultado.setText(""); 
    }//GEN-LAST:event_CaixaLimparActionPerformed

    private void CaixaCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaCalcularActionPerformed
        Peso=Float.valueOf(CaixaPeso.getText());
        Altura=Float.valueOf(CaixaAltura.getText());
        IMC= Peso/(Altura*Altura);
        CaixaResultado.setText(verificaIndice(IMC));
        
    }//GEN-LAST:event_CaixaCalcularActionPerformed

    private void CaixaSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaSairActionPerformed
        this.dispose();
        new Tela_Masculino().setVisible(false);
    }//GEN-LAST:event_CaixaSairActionPerformed

    private void CaixaVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaixaVoltarActionPerformed
       this.dispose();
       new Tela_IMC().setVisible(true);
    }//GEN-LAST:event_CaixaVoltarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Tela_Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Tela_Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Tela_Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Tela_Masculino.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Tela_Masculino().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField CaixaAltura;
    private javax.swing.JButton CaixaCalcular;
    private javax.swing.JButton CaixaLimpar;
    private javax.swing.JTextField CaixaPeso;
    private javax.swing.JTextArea CaixaResultado;
    private javax.swing.JButton CaixaSair;
    private javax.swing.JButton CaixaVoltar;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables

    private String verificaIndice(float IMC) {
        String result=null;
        if (IMC<=20.0)
            result="Seu IMC é: "+IMC+" - Classificação: Abaixo Normal \nProcure um médico. Algumas pessoas têm um baixo peso\npor características do seu organismo e tudo bem. Outras\npodem estar enfrentando problemas, como a desnutrição.\nÉ preciso saber qual é o caso.";
        else if ((IMC>=20.1)&&(IMC<=24.9))
            result="Seu IMC é: "+IMC+" - Classificação: Normal \nQue bom que você está com o peso normal! E o melhor\njeito de continuar assim é mantendo um estilo de vida\nativo e uma alimentação equilibrada. ";
         else if ((IMC>=25.0)&&(IMC<=29.9))
            result="Seu IMC é: "+IMC+" - Classificação: Sobrepeso \nEle é, na verdade, uma pré-obesidade e muitas pessoas\nnessa faixa já apresentam doenças associadas, como\ndiabetes e hipertensão. Importante rever hábitos e\nbuscar ajuda antes";
         else if ((IMC>=30.0)&&(IMC<=34.9))
            result="Seu IMC é: "+IMC+" - Classificação: Obesidade I \nSinal de alerta! Chegou na hora de se cuidar, mesmo\nque seus exames sejam normais. Vamos dar início a\nmudanças hoje! Cuide de sua alimentação. Você precisa\niniciar um acompanhamento";
         else if ((IMC>=35.0)&&(IMC<=39.9))
            result="Seu IMC é: "+IMC+" - Classificação: Obesidade II \nMesmo que seus exames aparentem estar normais, é\nhora de se cuidar, iniciando mudanças no estilo de\nvida com o acompanhamento próximo de profissionais\nde saúde.";
         else if (IMC>=40.0)
            result="Seu IMC é: "+IMC+" - Classificação: Obesidade III \nAqui o sinal é vermelho, com forte probabilidade de já\n existirem doenças muito graves associadas.\nO tratamentodeve ser ainda mais urgente.";
        else
             result=+IMC+": Seu IMC não coexiste, tu quebraste o programa...";
        
        return result;
    }
}
